### ISSUE TITLE
Skin weights export/import broken in Maya2022

### ISSUE THREAD

**Issue by sowwic** [sowwic/luna#7]
RuntimeError when creating **MFnSet**.
```
[luna][ERROR] SkinManager: Failed to export body_ply skin body_ply_skin
Traceback (most recent call last):
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 59, in export_single
    skin.export_data(new_file, fmt=self.file_format)
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 169, in export_data
    self.collect_data()
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 163, in collect_data
    self.collect_inluence_weights()
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 146, in collect_inluence_weights
    weights = self.get_current_weights()
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 137, in get_current_weights
    dag_path, components = self.get_geometry_components()
  File "D:\Repos\luna\luna_rig\importexport\skin.py", line 127, in get_geometry_components
    fn_set = om.MFnSet(self.pynode.__apimfn__().deformerSet())
RuntimeError: (kFailure): Unexpected Internal Failure
```

**Comment by sowwic** [comment]
Related: https://github.com/mgear-dev/mgear_core/issues/84

**Comment by sowwic** [comment]
https://github.com/mgear-dev/mgear4/commit/cb2084144be5b89face880681185d78ba08f688f
